# coding: utf-8

module ZapAttack::UI
  PROXY_INITIATOR = 1
  ACTIVE_SCANNER_INITIATOR = 2
  SPIDER_INITIATOR = 3
  FUZZER_INITIATOR = 4
  AUTHENTICATION_INITIATOR = 5
  MANUAL_REQUEST_INITIATOR = 6
  CHECK_FOR_UPDATES_INITIATOR = 7
  BEAN_SHELL_INITIATOR = 8
  ACCESS_CONTROL_SCANNER_INITIATOR = 9
  AJAX_SPIDER_INITIATOR = 10
  FORCED_BROWSE_INITIATOR = 11
  TOKEN_GENERATOR_INITIATOR = 12

  public_constant :PROXY_INITIATOR, :ACTIVE_SCANNER_INITIATOR, :SPIDER_INITIATOR, :FUZZER_INITIATOR, :AUTHENTICATION_INITIATOR, :MANUAL_REQUEST_INITIATOR, :CHECK_FOR_UPDATES_INITIATOR, :BEAN_SHELL_INITIATOR, :ACCESS_CONTROL_SCANNER_INITIATOR, :AJAX_SPIDER_INITIATOR, :FORCED_BROWSE_INITIATOR, :TOKEN_GENERATOR_INITIATOR
end
